openapi: 3.0.3
info:
  version: 1.0.0
  title: RBKmoney Fraudbusters Management API
  description:
    $ref: './docs/api.md'
  termsOfService: 'https://rbk.money/'
  contact:
    name: RBKmoney Support Team
    email: support@rbk.money
    url: 'https://developer.rbk.money'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
security:
  - bearer: []
tags:
  - name: audit
    x-displayName: Audit
  - name: notification
    x-displayName: Notifications
  - name: group
    x-displayName: Groups
  - name: group-reference
    x-displayName: Groups reference
  - name: lists
    x-displayName: Lists
  - name: emulation
    x-displayName: Emulation
  - name: load-data
    x-displayName: Load data
  - name: template
    x-displayName: Templates
  - name: reference
    x-displayName: References
paths:
  # Audit
  /audit/commandTypes:
    $ref: ./paths/audit/getCommandTypes.yaml
  /audit/filter:
    $ref: ./paths/audit/filterLogs.yaml
  /audit/objectTypes:
    $ref: ./paths/audit/getObjectTypes.yaml

  # Notifications
  /notification:
    $ref: ./paths/notification/createOrUpdateNotification.yaml
  /notification/{name}:
    $ref: ./paths/notification/removeNotification.yaml
  /notification/validate:
    $ref: ./paths/notification/validateNotification.yaml

  # Notifications channel
  /notification/channel:
    $ref: ./paths/notification/channel/createChannel.yaml
  /notification/channel/{name}:
    $ref: ./paths/notification/channel/removeChannel.yaml

  # Load data
  /payment/load-data/fraud:
    $ref: ./paths/payment/load-data/loadFraudTransactions.yaml

  # Groups
  /payment/group:
    $ref: ./paths/payment/group/insertGroup.yaml
  /payment/group/{groupId}:
      $ref: ./paths/payment/group/removeGroup.yaml
  /payment/group/filter:
    $ref: ./paths/payment/group/filterGroups.yaml
  /payment/group/{id}:
    $ref: ./paths/payment/group/getGroup.yaml

  # Groups reference
  /payment/group/{id}/reference:
    $ref: ./paths/payment/group/reference/insertGroupReferences.yaml
  /payment/group/{id}/reference/remove:
    $ref: ./paths/payment/group/reference/removeGroupReference.yaml
  /payment/group/reference/filter:
    $ref: ./paths/payment/group/reference/filterGroupsReferences.yaml

  # Lists
  /payment/lists:
    $ref: ./paths/payment/lists/insertRow.yaml
  /payment/lists/{id}:
    $ref: ./paths/payment/lists/removeRow.yaml
  /payment/lists/availableListNames:
    $ref: ./paths/payment/lists/getAvailableListNames.yaml
  /payment/lists/filter:
    $ref: ./paths/payment/lists/filterLists.yaml

  # Templates
  /payment/template:
    $ref: ./paths/payment/template/insertTemplate.yaml
  /payment/template/{id}:
    $ref: ./paths/payment/template/removeTemplate.yaml
  /payment/template/filter:
    $ref: ./paths/payment/template/filterTemplates.yaml
  /payment/template/names:
    $ref: ./paths/payment/template/getTemplateNames.yaml
  /payment/template/validate:
    $ref: ./paths/payment/template/validateTemplate.yaml

  # References
  /payment/reference:
    $ref: ./paths/payment/reference/insertReferences.yaml # /template/references
  /payment/reference/{id}:
    $ref: ./paths/payment/reference/removeReference.yaml # /template/{templateId}/reference/{id}
  /payment/reference/filter:
    $ref: ./paths/payment/reference/filterReferences.yaml

  # Default references
  /payment/reference/default:
    $ref: ./paths/payment/reference/default/insertDefaultReference.yaml # /template/{id}/default
  /payment/reference/default/{id}:
    $ref: ./paths/payment/reference/default/removeDefaultReference.yaml # /template/{id}/default
  /payment/reference/default/filter:
    $ref: ./paths/payment/reference/default/filterDefaultReferences.yaml

  # Emulation
  /payment/emulation:
    $ref: ./paths/payment/emulation/getTemplatesFlow.yaml # /rules

servers:
  - url: 'https://fb-management:8080/fb-management/v1'

components:
  securitySchemes:
    bearer:
      $ref: './components/security-schemes/Bearer.yaml'
