openapi: 3.0.3
info:
  version: 1.0.0
  title: RBKmoney Fraudbusters Management API
  description:
    $ref: './docs/api.md'
  termsOfService: 'https://rbk.money/'
  contact:
    name: RBKmoney Support Team
    email: support@rbk.money
    url: 'https://developer.rbk.money'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
security:
  - bearerAuth: []
tags:
  - name: error-codes
    x-displayName: Коды ошибок
    description:
      $ref: './docs/error-codes.md'
  - name: audit
    x-displayName: Audit
  - name: notification
    x-displayName: Notifications
  - name: group
    x-displayName: Groups
  - name: group-reference
    x-displayName: Groups reference
  - name: lists
    x-displayName: Lists
  - name: emulation
    x-displayName: Emulation
  - name: load-data
    x-displayName: Load data
  - name: template
    x-displayName: Templates
  - name: reference
    x-displayName: References
paths:
  # Audit
  /audit/commandTypes:
    $ref: ./paths/audit/getCommandTypes.yaml
  /audit/filter:
    $ref: ./paths/audit/filterLogs.yaml
  /audit/objectTypes:
    $ref: ./paths/audit/getObjectTypes.yaml

  # Notifications
  /notification:
    $ref: ./paths/notification/createOrUpdateNotification.yaml
  /notification/{name}:
    $ref: ./paths/notification/removeByName.yaml
  /notification/validate:
    $ref: ./paths/notification/validateNotification.yaml

  # Notifications channel
  /notification/channel/{name}:
    $ref: ./paths/notification/channel/createChannel.yaml

  # Load data
  /load-data/fraud:
    $ref: ./paths/load-data/loadFraudTransactions.yaml

  # Groups
  /group:
    $ref: ./paths/group/insertGroup.yaml
  /group/{groupId}:
      $ref: ./paths/group/removeGroupById.yaml
  /group/filter:
    $ref: ./paths/group/filterGroups.yaml
  /group?groupId={id}:
      $ref: ./paths/group/getGroupById.yaml

  # Groups reference
  /group/{id}/reference:
    $ref: ./paths/group/reference/insertGroupReferences.yaml
  /group/{id}/reference/remove:
    $ref: ./paths/group/reference/removeGroupReferenceById.yaml
  /group/reference/filter:
    $ref: ./paths/group/reference/filterGroupsReferences.yaml
  /group/{groupId}/reference:
    $ref: ./paths/group/reference/getGroupReferencesByGroupId.yaml

  # Lists
  /lists:
    $ref: ./paths/lists/insertRowToList.yaml
  /lists/{id}:
    $ref: ./paths/lists/removeRowFromListById.yaml
  /lists/availableListNames:
    $ref: ./paths/lists/getAvailableListNames.yaml
  /lists/filter:
    $ref: ./paths/lists/filterLists.yaml

  # Templates
  /template:
    $ref: ./paths/template/insertTemplate.yaml
  /template/{id}:
    $ref: ./paths/template/removeTemplateById.yaml
  /template/filter:
    $ref: ./paths/template/filterTemplates.yaml
  /template/names:
    $ref: ./paths/template/getTemplateNames.yaml
  /template/validate:
    $ref: ./paths/template/validateTemplate.yaml

  # References
  /reference:
    $ref: ./paths/reference/insertReferences.yaml # /template/references
  /reference/{id}:
    $ref: ./paths/reference/removeReferences.yaml # /template/{templateId}/reference/{id}
  /reference/filter:
    $ref: ./paths/reference/filterReferences.yaml

  # Default references
  /reference/default:
    $ref: ./paths/reference/default/insertDefaultReference.yaml # /template/{id}/default
  /reference/default/{id}:
    $ref: ./paths/reference/default/removeDefaultReference.yaml # /template/{id}/default
  /reference/default/filter:
    $ref: ./paths/reference/default/filterDefaultReferences.yaml

  # Emulation
  /emulation:
    $ref: ./paths/emulation/getTemplatesFlowByPartyAndShop.yaml # /rules

servers:
  - url: 'https://fb-management:8080/fb-management/v1'

components:
  parameters:
    sortOrder:
      name: sortOrder
      in: query
      required: false
      schema:
        type: string
        enum:
          - ASC
          - DESC
          - DEFAULT
    initiator:
      name: initiator
      in: query
      required: true
      schema:
        type: string
    searchValue:
      name: searchValue
      in: query
      schema:
        type: string
    sortBy:
      name: sortBy
      in: query
      schema:
        type: string
    sortFieldValue:
      name: sortFieldValue
      in: query
      schema:
        type: string
    lastId:
      name: lastId
      in: query
      schema:
        type: string
    size:
      name: size
      in: query
      schema:
        type: integer
        format: int32
